version: '3.9'

services:
  postgres:
    container_name: postgres-cursos-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cursos_db
